name: Deploy AWS RDS with VPC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.11

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ap-southeast-1
        stack-name: my-stack
        template: ./cloudformation-template.yaml
        parameters: |
            VPC CIDR=10.0.1.0/24
            RDS StorageEncryptionKey=aws/rds
            DBInstanceType=db.t3.micro
            AutomaticBackupRetention=7


    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -auto-approve
